# Generated by Django 4.1.7 on 2023-03-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmplatform_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='amount_of_time',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
